import PDFDocument from 'pdfkit';
import { formatDate, formatDateShort } from '../../../shared/formatters.js';
import { COMPLAINT_STATUSES } from '../../../shared/constants.js';

const COLS = [
  { key: 'idx', label: '#', width: 22 },
  { key: 'title', label: 'Title', width: 118 },
  { key: 'category', label: 'Category', width: 88 },
  { key: 'status', label: 'Status', width: 62 },
  { key: 'priority', label: 'Priority', width: 46 },
  { key: 'location', label: 'Location', width: 78 },
  { key: 'date', label: 'Date', width: 62 },
  { key: 'student', label: 'Student', width: 55 },
];
const PAGE_MARGIN = 40;

/**
 * Builds a PDF report as a Buffer. We use pdfkit — a pure-JS PDF writer
 * with no external binary — instead of the "html-pdf-node" style tools
 * that render a real headless Chrome under the hood. Headless Chrome
 * needs ~300-500MB of RAM per render, which routinely OOM-kills on
 * Render's free tier (512MB total). pdfkit draws the PDF directly, so
 * it has no such requirement and simply cannot fail that way.
 *
 * @param {object} params
 * @param {Array}  params.complaints   plain objects (already populated/lean)
 * @param {object} params.filters      { status, category, departmentId, dateFrom, dateTo }
 * @param {string} params.generatedBy  name of the admin who generated the report
 */
export function generateComplaintReportPDF({ complaints, filters = {}, generatedBy }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4', bufferPages: true });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ---- Header ---------------------------------------------------
    doc
      .fillColor('#0f172a')
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('International Islamic University Chittagong', { align: 'center' });
    doc
      .fillColor('#475569')
      .fontSize(11)
      .font('Helvetica')
      .text('Campus Complaint Management — Report', { align: 'center' });
    doc.moveDown(0.8);

    doc.fillColor('#64748b').fontSize(9);
    doc.text(`Generated: ${formatDate(new Date())}`);
    if (generatedBy) doc.text(`Generated by: ${generatedBy}`);
    const filterDescription = describeFilters(filters);
    doc.text(`Filters: ${filterDescription}`);
    doc.moveDown(0.6);

    // ---- Summary counts --------------------------------------------
    const counts = Object.fromEntries(COMPLAINT_STATUSES.map((s) => [s, 0]));
    complaints.forEach((c) => {
      if (counts[c.status] !== undefined) counts[c.status] += 1;
    });

    doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold').text('Summary');
    doc.font('Helvetica').fontSize(9).fillColor('#334155');
    const summaryLine = [`Total: ${complaints.length}`, ...COMPLAINT_STATUSES.map((s) => `${s}: ${counts[s]}`)].join(
      '     '
    );
    doc.text(summaryLine);
    doc.moveDown(0.8);

    // ---- Table -------------------------------------------------------
    drawTableHeader(doc);
    complaints.forEach((c, i) => {
      ensureRowSpace(doc);
      drawRow(doc, {
        idx: String(i + 1),
        title: c.title,
        category: c.category,
        status: c.status,
        priority: c.priority,
        location: c.location,
        date: formatDateShort(c.createdAt),
        student: c.isAnonymous ? 'Anonymous' : c.studentId?.name || '—',
      });
    });

    // ---- Footer page numbers ----------------------------------------
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .fillColor('#94a3b8')
        .text(`Page ${i + 1} of ${range.count}`, PAGE_MARGIN, doc.page.height - 30, {
          width: doc.page.width - PAGE_MARGIN * 2,
          align: 'center',
        });
    }

    doc.end();
  });
}

function describeFilters(filters) {
  const parts = [];
  if (filters.status) parts.push(`status=${filters.status}`);
  if (filters.category) parts.push(`category=${filters.category}`);
  if (filters.departmentId) parts.push('department filtered');
  if (filters.dateFrom) parts.push(`from ${formatDateShort(filters.dateFrom)}`);
  if (filters.dateTo) parts.push(`to ${formatDateShort(filters.dateTo)}`);
  return parts.length ? parts.join(', ') : 'All complaints';
}

function drawTableHeader(doc) {
  const y = doc.y;
  doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff');
  doc.rect(PAGE_MARGIN, y, tableWidth(), 18).fill('#0f172a');
  let x = PAGE_MARGIN;
  COLS.forEach((col) => {
    doc.fillColor('#ffffff').text(col.label, x + 3, y + 5, { width: col.width - 6, ellipsis: true });
    x += col.width;
  });
  doc.y = y + 18;
}

function drawRow(doc, rowData) {
  const y = doc.y;
  const rowHeight = 16;
  let x = PAGE_MARGIN;
  doc.font('Helvetica').fontSize(7.5).fillColor('#1e293b');
  COLS.forEach((col) => {
    doc.text(String(rowData[col.key] ?? '—'), x + 3, y + 4, {
      width: col.width - 6,
      height: rowHeight - 4,
      ellipsis: true,
    });
    x += col.width;
  });
  doc
    .moveTo(PAGE_MARGIN, y + rowHeight)
    .lineTo(PAGE_MARGIN + tableWidth(), y + rowHeight)
    .lineWidth(0.5)
    .strokeColor('#e2e8f0')
    .stroke();
  doc.y = y + rowHeight;
}

function ensureRowSpace(doc) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + 16 > bottom) {
    doc.addPage();
    drawTableHeader(doc);
  }
}

function tableWidth() {
  return COLS.reduce((sum, c) => sum + c.width, 0);
}
